backend:
  name: github
  repo: okeneko/vesuvio79

media_folder: static/assets
public_folder: assets
site_url: https://vesuvio79.netlify.com
# logo_url: https://vesuvio79.netlify.com/icons/icon-256x256.png

collections:
  - label: "Menù"
    name: "menu"
    format: "json"
    files:
      - label: "Il Menù"
        name: "menu"
        file: "src/content/menu.json"
        fields:
          - label: "Paste"
            name: "paste"
            widget: "list"
            fields:
              - label: "Nome"
                name: "nome"
                widget: "string"
              - label: "Prezzo"
                name: "prezzo"
                widget: "number"
                valueType: "float"
                min: 0
          - label: "Pizze"
            name: "pizze"
            widget: "list"
            fields:
              - label: "Nome"
                name: "nome"
                widget: "string"
              - label: "Prezzo"
                name: "prezzo"
                widget: "number"
                valueType: "float"
                min: 0
          - label: "Risotti"
            name: "risotti"
            widget: "list"
            fields:
              - label: "Nome"
                name: "nome"
                widget: "string"
              - label: "Prezzo"
                name: "prezzo"
                widget: "number"
                valueType: "float"
                min: 0
